### ISSUE TITLE
new project, second, third

### ISSUE THREAD

**Issue by yanis7774** [decentraland/cli#102]
When I wanna create a new project, CLI: 

```
MacBook-Pro-2:decentraland hsbs$ npm start init

> decentraland@0.5.1 start /Users/hsbs/.npm-global/lib/node_modules/decentraland
> (mkdir tmp > /dev/null 2>&1 || true) && cd tmp && NODE_ENV=dev ../bin/dcl "init"

Project already exists!

```

How can I init and develop a few different scenes? And re-init existing project (without delete files manualy)

**Comment by eordano** [comment]
Hi there,

Please install the CLI globally: `npm i -g decentraland`. It works similarly as `git`, but in order to create a project it makes sure you do so on an empty folder
