### ISSUE TITLE
upgrade: Check for root/access permissions before attempting install

### ISSUE THREAD

**Issue by eordano** [decentraland/cli#109]
Right now, the error the user is shown when they have no permissions is quite strange

![image](https://user-images.githubusercontent.com/42750/37574542-574e630a-2b00-11e8-9a6d-9f27befe65d9.png)

**Comment by menduz** [comment]
we should **not** install anything as root. What is the description of this error? how do we know having root access will fix it?

**Comment by eordano** [comment]
`npm i -g` requires root on some systems (linux)
