### ISSUE TITLE
Fix "Error: cannot find module "(current dir)"

### ISSUE THREAD

**Issue by eordano** [decentraland/cli#12]

**Comment by michaltakac** [comment]
`budo` should serve `scene.html` from DCL project directory (where the `scene.json` resides) but right now it thinks the directory is a module. It should serve static `scene.html`.
https://github.com/mattdesl/budo/issues/103

**Comment by michaltakac** [comment]
It also seems like that #14 would solve the issue, because we need to serve just the static assets.
https://github.com/mattdesl/budo/blob/master/docs/api-usage.md#http-server
https://github.com/mattdesl/budo/blob/master/docs/api-usage.md#opts -> `staticOptions`
