### ISSUE TITLE
Serve "scene.html" as default

### ISSUE THREAD

**Issue by eordano** [decentraland/cli#14]

**Comment by michaltakac** [comment]
`budo` as a static file server
https://github.com/mattdesl/budo/blob/master/docs/api-usage.md#http-server
For setting different default index, I guess this should do:
https://github.com/mattdesl/budo/blob/master/docs/api-usage.md#opts -> `staticOptions` -> { index: 'scene.html' }

**Comment by cazala** [comment]
@michaltakac yep that's what I did, it works, but I'm having problems to serve `tmp/dcl-app` when `isDev` is `true`. It looks like it's trying to require the directory?

```js
const baseDir = isDev ? './tmp/dcl-app/' : './'
  budo(baseDir, {
    host: '0.0.0.0',
    live: true,
    port: 2044,
    stream: process.stdout,
    staticOptions: {
      index: 'scene.html'
    }
  });
```

```
Cannot find module '/Users/juancazala/Code/GitHub/cli/tmp/dcl-app'
```

It works fine if I leave the `baseDir` as `'.'`

**Comment by cazala** [comment]
nevermind, this one works:

```js
  const baseDir = isDev ? './tmp/dcl-app/' : '.'
  budo('.', {
    host: '0.0.0.0',
    live: baseDir,
    dir: baseDir,
    port: 2044,
    stream: process.stdout,
    staticOptions: {
      index: 'scene.html'
    }
  });
```
