### ISSUE TITLE
Create a nice looking UI for publishing to Ethereum

### ISSUE THREAD

**Issue by eordano** [decentraland/cli#15]
It would be nice to have a better web user interface than the current one (`dcl deploy` when the blockchain info is not up to date). Needs design.

**Comment by bnolan** [comment]
@eordano can you describe what you mean by a nice looking UI? Do you mean a react app we open in a browser? Or do you mean an interactive command line UI?

**Comment by belohlavek** [comment]
Gotcha, let's review this with mat and plan ahead for a future sprint
