### ISSUE TITLE
dcl deploy ：Could not connect to web3

### ISSUE THREAD

**Issue by nocb** [decentraland/cli#150]
dcl deploy 
Uploading project to IPFS:
Error trying to connect Ethereum wallet: Could not connect to web3 

the dcl  version：Decentraland CLI v1.0.2 
os： mac  10.12.6 

1.0.0   is ok ！

---
hansen

**Comment by belohlavek** [comment]
We have an issue with an internal dependency used to connect to the Blockchain, will publish a hotfix soon.

Thanks for your patience.

**Comment by ztnark** [comment]
Any update?

**Comment by belohlavek** [comment]
This should be fixed in version `1.0.3`. Be careful while deploying as the world is not public yet and you won't be able to view your uploaded scene.

Closing.
