### ISSUE TITLE
As a developer, I want to check easily if an object is near a parcel boundary

### ISSUE THREAD

**Issue by Nyc0las** [decentraland/cli#154]
An object mustn't goes outside our land. So in order to create moving object which avoid going outside on their own, we should be able to easily detect the boundaries (which differs depending on the number and position of parcels).
For example we could have a collision detection system, or at least the coordinates of each boundary (with coordinates we could also easily get the distance to the boundaries, which is a good thing).
Maybe we could also have a system where, for each parcel, we know which square side is forbidden and which one leads to another of our parcel?

**Comment by belohlavek** [comment]
The next release of the metaverse-api contains changes on the way triangle/boundaries errors are displayed. Additionally, new developers tools as well so you'll be able to se the scene in wireframe mode and the position of entities in runtime, further helping you debugging out-of-boundaries issues.

Stay tuned!

**Comment by belohlavek** [comment]
check the latest release

**Comment by belohlavek** [comment]
Please reopen on https://github.com/decentraland/sdk-issues/issues
