### ISSUE TITLE
metaverse-compiler bin is missing on Windows

### ISSUE THREAD

**Issue by cazala** [decentraland/cli#158]
There seems to be an issue with the `metaverse-compiler` on Windows, https://github.com/cazala/decentraland-shoal-scene/issues/1, the `metaverse-compiler` bin file is missing.

**Comment by belohlavek** [comment]
`dcl preview` won't fail with the latest RC

**Comment by belohlavek** [comment]
check the lqtest release

**Comment by cazala** [comment]
thqnk you <3
