### ISSUE TITLE
Some issues with Windows quickstart instructions

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#160]
In step 6, the wording "Install git and when prompted choose to install git bash" makes it sound like you will get a popup prompt or something.  I THINK what is meant here is that in the step where it shows you what you can install, you need to be sure that bash is checked.  There isn't any other place where that is prompted in the install i just did.

In step 7, it sounds like selecting Nano is a requirement.  If one has Notepad++, which is a commonly used editor, that is also a reasonable choice

8. All of the following words should be bolded:
Use Git from the Windows Command Prompt

9. I was never asked about an SSH executable.  I noticed this the last couple of times I installed also.

13. I never received the opportunity to answer these question (I was installing Git v2.17.0)

14. The biggest thing I see is that in the Windows version of the install, there is never an npm i decentraland.  This should be a step 14 in the Windows version

(Is the command the same in Windows as it is in Linux?

**Comment by cfravel** [comment]
A couple of other things I notice:

- The general introduction mentions Python, but the step by step doesn't.  Should be added
- At the top it gives an npm i -g decentraland, but then later it gives a different parameter for Linux.  Confusing.  Probably best to clarify full, numbered steps for each OS, start to finish, in order.

**Comment by fmiras** [comment]
new docs here: https://docs.decentraland.org/getting-started/installation-guide
