### ISSUE TITLE
scene.xml positioning on obj-model seems to follow the last object. 

### ISSUE THREAD

**Issue by leobelen** [decentraland/cli#163]
Working with static scenes and adding two obj-model objects, it seems that the positioning is affected by the last object placed. 

In 
scene>
    	obj-model src="1.obj" mtl="1.mtl" position="4 2 4" scale="2 2 2"/>
	obj-model src="2.obj" mtl="2.mtl" position="0 2 0" scale="2 2 2"/>
/scene>
 
 <img width="957" alt="screen shot 2018-05-24 at 14 47 11" src="https://user-images.githubusercontent.com/797345/40502530-9f4b2d42-5f61-11e8-94b5-62b01ac8161b.png">

Such result is  explainable only by the fact that the second object is laid out based on the previous object's location. Is this the expected behavior?

**Comment by belohlavek** [comment]
XML does not support self closing tags. Other than that please update your example, it seems corrupted.

**Comment by belohlavek** [comment]
this issue is a month old an we have a new breaking release of metavers-api now, will reopen if needed
