### ISSUE TITLE
Running the preview can only be terminated by brute force on macOs. 

### ISSUE THREAD

**Issue by leobelen** [decentraland/cli#164]
When running the preview, exiting from ```dcl preview``` does not terminate the program, instead it keeps running as a service until it gets killed by brute force (```kill -9 <pid_id>```)... probably a new option may need to be added as to stop said service and an option to run as a service or as a program.

**Comment by belohlavek** [comment]
Can you share more info? Stopping the preview with CTRL+C successfully stops
`501 52854  4620   0  8:15PM ttys006    0:04.48 node --no-warnings /Users/dani/.nvm/versions/node/v10.1.0/bin/dcl preview`

**Comment by leobelen** [comment]
@belohlavek, thanks for the quick response. It seems that CTRL+C does not indeed stop the server. In fact, if you try to restart the server, it seems that now it does not say that there is a port in use, however, if you execute ```ps -fu user | grep dcl``` you will see it as process, consuming quite a lot of resources. Never-the-less, dcl does not accept connections in this case, which makes it fairly strange. 

I am using homebrew's node@8 on macOs High Sierra (fully updated).

**Comment by belohlavek** [comment]
Closing as this issue is no longer valid, we clean up the server properly and we find other available ports if needed.
