### ISSUE TITLE
Error about linker-app absent

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#168]
I am getting an ENOLOCAL error about decentraland/linker-app
STILL getting the same error I got on windows at dcl init (see #161).  
Obviously nothing to do with windows.  
I'm clearly missing some other piece of the process:

Steps:
1. Installed an ubuntu virtual server at my hosting provider
2. Installed all of the prerequisites installed that I could figure out, 
    Python 2.7.14
    Nodejs 8.11.2
    npm 5.6.0
    IPFS  0.4.10
    Git 2.7.4
3. sudo npm i -g --unsafe-perm decentraland@rc

// Error that I received:

npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../usr/lib/node_modules/decentraland/linker-app" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cfravel/.npm/_logs/2018-05-27T09_21_21_093Z-debug.log

**Comment by belohlavek** [comment]
Try the new RC version

**Comment by belohlavek** [comment]
check the latest release
