### ISSUE TITLE
wrong link to docs created with $dcl init

### ISSUE THREAD

**Issue by jschiarizzi** [decentraland/cli#177]
Running $ dcl init

Created a readme with a link to https://docs.decentraland.org/docs which is a 404. It should be https://docs.decentraland.org/

**Comment by belohlavek** [comment]
You mean the repo README? `dcl init` doesn't generate a README :)

**Comment by jschiarizzi** [comment]
hmmm maybe? I just remember that when I did dcl init my readme had the wrong link, but it is entirely possible it was left over from cloning a repo or something.

**Comment by belohlavek** [comment]
I'll asume it was the repo README (which I updated recently) please feel free to comment and I will reopen if needed.
