### ISSUE TITLE
difference of using scale  

### ISSUE THREAD

**Issue by oscnet** [decentraland/cli#191]
create static  scene   using `dcl init` ，add scene.xml
```
<box 
  position="5  0  2 " 
  color="#ff00aa" 
  scale="3" 
/>
```
when preview , the real scale is 1 , with no  error message

```
<box 
  position="5  0  2 " 
  color="#ff00aa" 
  scale="3 3 3" 
/>
```
this worked.

ps:
create Dynamic scene (single player)  using `dcl init`, add to  scene.tsx:
```
<box 
  position={ { x: 5, y: 0, z: 2 } } 
  color="#ff00aa" 
  scale={3} 
/>
```
also  worked .

**Comment by belohlavek** [comment]
Please reopen on https://github.com/decentraland/sdk-issues/issues
