### ISSUE TITLE
The documentation for Node JS points at CLI github, not at Node.js

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#211]
Steps to reproduce:
1. Go to docs on website
2. See the prereqs
3. Click on NodeJS
// expected: go to Node.js installation source
// actual: go to CLI github
4. On the CLI readme.md, click the NodeJS linke
// expected: go to Node.js installation source
// actual: go to CLI github

**Comment by cfravel** [comment]
Probably should go to
https://nodejs.org/en/download/

**Comment by fmiras** [comment]
Thank you @cfravel! Here's the fix f4d40cfc39e380f18dd5d3dcdbc1661b7222f7b2

**Comment by cfravel** [comment]
@fmiras 

It is still incorrect in the website.
