### ISSUE TITLE
dcl start and `npm run watch`

### ISSUE THREAD

**Issue by tcrowe** [decentraland/cli#226]
Hi Decentraland Team,

If I run `dcl start` it also runs, or attempts to run, `npm run watch` even if I don't have that script in my `./package.json`.

`./package.json#scripts`

```json
"watch": "echo 'TEST TEST not sure why this is running TEST TEST'",
"dev-compile": "decentraland-compiler build.json --watch || true",
"dev-dcl-start": "dcl start --port 8834 --no-browser --no-watch || true",
"dev-server": "nodemon -q -L -d 1 -w '*.ts' --ext ts --exec ts-node --project tsconfig-server.json --pretty server.ts || true"
```

As you can see this is not part of a `dcl init` generated workflow. I tried using `--no-watch` but I think that has a different function.

This file is running `npm run watch`:
https://github.com/decentraland/cli/blob/d0473f7956ca4528ca2884fa6ea96271eb6f3833/src/utils/moduleHelpers.ts#L24

Ideally `dcl` CLI will not tie itself to specific `./package.json#scripts`. Maybe it could run whatever that `watch` script runs.

What do you think?

-Tony

**Comment by matiasbargas** [comment]
We depend on the watch script to run the preview. This is because the preview is imported from one of the dependencies and not bundled in the dcl package.
