### ISSUE TITLE
A little bandwidth saving

### ISSUE THREAD

**Issue by tcrowe** [decentraland/cli#227]
The online check is pulling the whole page:
https://github.com/decentraland/cli/blob/d0473f7956ca4528ca2884fa6ea96271eb6f3833/src/utils/moduleHelpers.ts#L104

If you do something like `https://decentraland.org/online-check.json` that will be pretty good.

**Comment by fmiras** [comment]
That's a pretty good idea we're going to work in something like that, it should be more like a _ping_ instead of pulling a whole page

**Comment by matiasbargas** [comment]
https://github.com/decentraland/cli/pull/229
