### ISSUE TITLE
`dcl init` compatibility and compilation

### ISSUE THREAD

**Issue by tcrowe** [decentraland/cli#228]
Each day in the chat someone is asking why `dcl init` wont work. Usually it's on Windows.

It fails on the install but does not report the error message:
https://github.com/decentraland/cli/blob/d0473f7956ca4528ca2884fa6ea96271eb6f3833/src/utils/moduleHelpers.ts#L13

---

Changing this to `npm install --ignore-scripts` will prevent npm from trying to compile optional C modules and default to JS. JS is the only thing which will be used in the browser anyway so this is okay. It seems to work when I tell people how to do it.

`child.on("error", ...)` handing would be good
`child.stderr.on("data", ...)` handing would be good as well

**Comment by fmiras** [comment]
Instead of just catching the error and find a work around we would prefer to detect the problem and validate before making the installation, can you describe us a little bit more of the context (OS version, Node version, etc.) so we can run some tests?

**Comment by tcrowe** [comment]
It's not a problem that Decentraland devs created. If you look at the modules that decentraland or decentraland-api pull in it attempts to compile C code or something.

New devs on Windows don't have any compiler so it doesn't totally work.

`--ignore-scripts` tells npm not to run `postinstall` bypassing compilation and defaulting to JS-only modules.

**Comment by tcrowe** [comment]
One way to test is get a fresh Windows VM and follow the [Installation Guide](https://docs.decentraland.org/getting-started/installation-guide/).

---

Find all dependencies with npm compilation scripts on Unix-like systems:

`grep -riIE --include package.json "prepublish|prepare|prepack|preinstall|install" node_modules`

Each of those results may try to compile some non-JS, non-node, dependencies. e.g. secp encryption

**Comment by fmiras** [comment]
This should be fixed with #323
