### ISSUE TITLE
Error when trying to run 'dcl link' / 'dcl deploy'

### ISSUE THREAD

**Issue by J-Gallo** [decentraland/cli#231]
Hi everyone !

I am having an issue when trying to deploy/link a scene.

After getting the message `Linking app ready at http://localhost:8000/linker` the browser opens as expected but I am getting the following:

https://puu.sh/BSbFj/61eed707bc.png
https://puu.sh/BSbFT/97bc55bdb7.png

This is happening on macOS Mojave version 10.14 both in Chrome and Firefox

**Comment by J-Gallo** [comment]
Update: This is only happening in 1.4.0. I went back to 1.3.1 and it is working as expected.

I will leave this issue open just for you to check but feel free to close it if you want

**Comment by matiasbargas** [comment]
Hello J-Gallo, 

We are aware of this problems and we are working to remove the link stage in the deploy. 

It should be available in the following weeks. 

Thank you for your help :)
