### ISSUE TITLE
Unable to use dcl deploy - IPFS Error

### ISSUE THREAD

**Issue by damo1884** [decentraland/cli#233]
Unable to use dcl deploy

----------
dcl deploy

  Tracked files:

    models/ball_rack_512x512.jpg (197812 bytes)
    models/ball_return_512x512.jpg (137856 bytes)
    models/bowling+alley.bin (857184 bytes)
    models/bowling+alley.gltf (228885 bytes)
    models/bowling_ball_tex1_512x256.jpg (164231 bytes)
    models/bowling_ball_tex3_512x256.jpg (109817 bytes)
    models/bowling_ball_tex4_512x256.jpg (192323 bytes)
    models/bowling_ball_tex5_512x256.jpg (197407 bytes)
    models/bowling_ball_tex6_512x256.jpg (141356 bytes)
    models/bowling_ball_tex7_512x256.jpg (102065 bytes)
    models/bowling_ball_tex8_512x256.jpg (209405 bytes)
    models/bowling_pin_normal_traditional_512x512.jpg (69755 bytes)
    models/bowling_pin_normal_traditional_512x512.jpg.jpg (69755 bytes)
    models/building_2048x2048.jpg (1032318 bytes)
    models/chairs_512x512.jpg (151098 bytes)
    models/hardwood_512x1024.jpg (163630 bytes)
    models/ice.png (3198 bytes)
    models/scorer_table_512x512.jpg (137485 bytes)
    models/target.jpg (244739 bytes)
    scene.js (442251 bytes)
    scene.json (579 bytes)

? You are about to upload 21 files (4853149 bytes). Do you want to continue? Yes
- Files uploaded to IPFS
- No IPNS found for coordinates 9,-30
⠙ Publishing IPNS for /ipfs/QmXjrAgivYUhjTPANcWoPUvHTe2FBu7FALWaD1ajbWR4P2
Failed to publish: no key by the given name or PeerID was found (try restarting your IPFS daemon)

--------

Here is my scene.json

{
  "display": {
    "title": "Decentraland Bowling and Curling Club"
  },
  "contact": {
    "name": "removed",
    "email": "removed"
  },
  "owner": "removed",
  "scene": {
    "estateId": "753",
    "parcels": [
      "9,-30",
      "9,-31"
    ],
    "base": "9,-30"
  },
  "communications": {
    "type": "webrtc",
    "signalling": "https://rendezvous.decentraland.org"
  },
  "policy": {
    "fly": true,
    "voiceEnabled": true,
    "blacklist": [],
    "teleportPosition": "0,0,0"
  },
  "main": "scene.js"
}

-------

Here is my IPFS Daemon

ipfs daemon
Initializing daemon...
Successfully raised file descriptor limit to 2048.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.21/tcp/4001
Swarm listening on /ip6/2601:640:8200:1340:1c5d:8500:7cf0:8f0d/tcp/4001
Swarm listening on /ip6/2601:640:8200:1340:2160:e7f5:b54f:9d8c/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmRHPVeaqnzyxXzkSZW6nJ9WR9tWJD7B2RQAHV1QJ8VgE7
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.21/tcp/4001
Swarm announcing /ip6/2601:640:8200:1340:1c5d:8500:7cf0:8f0d/tcp/4001
Swarm announcing /ip6/2601:640:8200:1340:2160:e7f5:b54f:9d8c/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

**Comment by fmiras** [comment]
@damo1884 all decentraland users are experimenting lots of problems with IPFS because although is a very powerful great technology for decentralising content it has also a lot of bad UX problems that we want to take care of by migrating to a new content server that we're developing and it uses IPFS behind the scenes (for more check this [pull request](https://github.com/decentraland/cli/pull/230).
