### ISSUE TITLE
Empty defaults look weird

### ISSUE THREAD

**Issue by NicoSantangelo** [decentraland/cli#30]
Running `dcl init` prompts the user for information. Some of if has a default value shown in parens but some fields don't have a default and look like this:

```
? Project title:  (DCL app) # <--- WITH DEFAULT

? Your MetaMask address: () <--- WITHOUT
```

It would be nice if we can remove the `()`, by removing the `default: ''` value on `inquirer.prompt`

**Comment by michaltakac** [comment]
Hmm, interesting, it actually fills the blanks with `""` like we want even without `default: ''` :D
Fix incoming!
