### ISSUE TITLE
commit 1.4.0-20181219155315.commit-690dd88 throws error during dcl deploy

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#301]
--- environment:
Chrome, Windows 10, no headset

---- Steps to reproduce
md 20181223-02
cd 20181223-02
npm rm -g decentraland
npm i -g decentraland@next
  decentraland@1.4.0-20181219155315.commit-690dd88
npm outdated -g decentraland
   Package                                   Current  Wanted  Latest  Location
   decentraland  1.4.0-20181219155315.commit-690dd88   1.4.0   1.4.0
// edit scene.json to point to some private land you own
dcl deploy

// expected: success
// actual
invalid json response body at https://content-service.decentraland.zone/content/status 
reason: Unexpected token p in JSON at position 4

--- Workaround:
// use one commit earlier:

md 2018-23-06-static
cd 2018-23-06-static
npm rm -g decentraland
npm i -g decentraland@1.4.0-20181217174426.commit-7fe2565
npm view decentraland-ecs
	decentraland-ecs@1.0.1-20181217200454.commit-97d3944
dcl init --boilerplate static
dcl start
Edit json for -some parcel you have upload rights to
dcl deploy
// success

**Comment by cfravel** [comment]
Workaround:
For now, use:
dcl deploy -f:

**Comment by fmiras** [comment]
Fixed https://github.com/decentraland/cli/pull/309
