### ISSUE TITLE
There is no explicit way to remove a deployed scene, or to move or subdivide a deployed multiparcel scene

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#304]
--- environment
Chrome, Windows 10, no HMD
npm i -g decentraland@1.4.0-20181217174426.commit-7fe2565

--- Steps to reproduce

Deploy a valid 2-parcel scene (Scene A)
// success
// and it looks right in alpha client

Deploy a 1-parcel scene to just one of the two parcels of the first scene (Scene B)
// expected error message: Cannot deploy a scene that overlaps with part of a previously deployed scene
// actual error message: Error: This address doesn't either own this LAND or have update permissions.

Decide to adjust the 2 parcel scene in order to effectively subdivide the two parcels apart.
//There isn't any explicit way to do this per the docs or UI.

---- Partial workaround if the base parcel is the same.
Deploy a 1 parcel scene (Scene C) to the BASE PARCEL of the multiparcel Scene A
// success
Try again to deploy the 1-parcel Scene B to its single parcel (that was a non-base parcel of Scene A)
// success

--- HOWEVER
This does NOT actually delete the base parcel, and it stands in the way of any new scene being uploaded to a different base parcel.
So, for example, if you want to move a scene south or west, the base parcel of the original scene, even if reduced to a 1-parcel empty scene, will keep the new scene from being uploaded
Example
Deploy a 4 parcel scene whose base parcel is its SW corner, at n,m
"Erase" it by uploading a 1 parcel scene at n,m
Redeploy the 4 parcel scene at n-1, m-1
// fails

**Comment by fmiras** [comment]
Removing a scene isn't supported. In the other hand, the CLI overrides any scene and also it know prompts a y/n question for that (#328)
