### ISSUE TITLE
Recent decentraland@next can deploy scene.xml static but not game.ts ecs scenes

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#307]
--- Environment
Windows 10, Chrome
Using build:
npm i -g decentraland@1.4.0-20181217174426.commit-7fe2565
(because, per #301, decentraland 1.4.0-20181219155315.commit-690dd88 1.4.0 1.4.0 throws an error during deploy)

--- Steps to reproduce
npm rm -g decentraland
npm i -g decentraland@1.4.0-20181217174426.commit-7fe2565

Create and go into a new directory D1
dcl init --boilerplate xml
edit the scene.json to point at 1 parcel of land that you have rights to upload to.
dcl start 
// see static scene objects
dcl deploy
// success
// Observe that parcel in the alpha client.decentraland.zone
// success: you see the static scene objects

Create and go into a new directory D2
dcl init --boilerplate ecs
edit the scene.json to point at 1 parcel of land that you have rights to upload to.
dcl start 
// see the rotating cube per ecs boilerplate
dcl deploy
// reports success
// Observe that parcel in the alpha client.decentraland.zone
**// Failure: nothing there**

**Comment by cfravel** [comment]
Retested with @next 1.4.0-20181219155315.commit-690dd88
using dcl deploy -f
Although now this very latest version doesn't throw and error, it still results in no visible scene in the alpha client

**Comment by fmiras** [comment]
Fixed https://github.com/decentraland/cli/pull/309
