### ISSUE TITLE
decentraland@next doesn't support texture-based materials on primitives in scene.xml static scenes

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#308]
--- environment
Windows 10, Chrome
Using decentraland@1.4.0-20181217174426.commit-7fe2565 because, as per #301, decentraland@next throws an error during dcl deploy

--- Steps to reproduce
dcl init --boilerplate static
create a simple scene with primitives and optionally gltfs.
add material(s) based on texture map image file
apply such material(s) to one or more of the primitive objects
dcl start
// expected: material appears on primitives
// actual: primitives are grey

// I attach an example scene.
// note my different syntactical attempts to get materials to work on the primitives

**Comment by cfravel** [comment]
[CC-ME.zip](https://github.com/decentraland/cli/files/2709596/CC-ME.zip)

**Comment by fmiras** [comment]
Referred to client project.
