### ISSUE TITLE
Differenciate between decentraland-ecs and decentraland-api users

### ISSUE THREAD

**Issue by belohlavek** [decentraland/cli#334]
For those uses who opted in, we should track if they are using the new version of the SDK (ecs) versus the old one.

**Comment by dnul** [comment]
we can still use the same field 'dclApiVersion' with a prefix like 
'decentraland-api=3.4.0' or 'decentraland-ecs=1.2.3'

**Comment by menduz** [comment]
we can release the ecs with a new major to continue the legacy of decentraland-api. Like
```
decentraland-api: 4.x.x
decentraland-ecs: >=5.x.x
```

does that work @dnul ?

**Comment by dnul** [comment]
sure

**Comment by fmiras** [comment]
Moved to client repo
