### ISSUE TITLE
You must completely overwrite every parcel of an old scene to reuse that land in other ways.

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#355]
Once a multi-parcel scene has been uploaded, if you later want to shrink it or remove it to allow a different scene to be uploaded to use part of the previous scene, you must overwrite every parcel of the old scene with something new, or else the old scene will assert itself, preventing a new/overlapping scene from using ANY of the old scene's parcels. This is even true if the old scene has no content.  DCL INFO shows that the writes over some of the old scenes parcels seem to have succeeded, but the client won't show any of the new content unless all of the old scene's parcels get written to to change the organization/use of its parcels.

For example if you have a deployed 3x1 parcels scene, and want to use the eastern two thirds of it for something else, leaving only the western parcel to contain the content (or blank) that was in the old scene, you must write over all four parcels before any of the old scene can be replaced.   Let's say you wanted to erase the entire 3x1 scene, and reuse the eastern 2 parcels of it.  You can't just write to the eastern parcels.  you must also upload something (blank or other content) to the western parcel, too, to get the eastern parcels to show the new content that's been deployed to them.

**Comment by cfravel** [comment]
This may be exactly what's intended (although it's interesting that it's the older content that predominates for some reason if two scenes conflict).
At the least, the dev docs should explain what's needed to clear content off of multiparcel scenes to reorganize the space.

**Comment by cfravel** [comment]
This sort of indicates the need to have a visual representation in the scene building tool of the boundaries of existing scenes.  New uploads to reorganize the space will need to see what old scene land needs to be written to to break up the old scene.

**Comment by cfravel** [comment]
Here is a specific example scenario for this issue.
https://docs.google.com/document/d/14B_ZtuIPf_nHPjAVBqeU4KTH21O_dw0Afp4FSqdYxu8/edit#heading=h.fc2x96i8wnni

**Comment by cfravel** [comment]
This may be more of a client issue than a dcl deploy issue

**Comment by twaldorf** [comment]
Thanks for the writeup on this. We're looking at bandaids + larger fixes for some of these kinks in the deploy UX.

**Comment by nchamo** [comment]
Hey @cfravel, just wanted to let you know that the new content server fixes this.

If you have a scene that is deployed in parcels A, B and C, and you deploy a new scene on parcel A, then B and C will be left empty, without the need for you to do an extra operation.

I'm closing this, but feel free to ping me if you have any questions
