### ISSUE TITLE
feat: remove segment production key from default env

### ISSUE THREAD

**Issue by dnul** [decentraland/cli#365]
# What? 

Change default env segment_key to **mjCV5Dc4VAKXLJAH5g7LyHyW1jrIR3to.**

only set  **sFdziRVDJo0taOnGzTZwafEL9nLIANZ3** for releases.

# Why? 

To avoid spilling events when doing development.
...

**Comment by menduz** [comment]
We can choose it by detecting some of the underscore-prefixed keys in the package.json that are added to an installed dependency

**Comment by fmiras** [comment]
5cdc0fbe84a8d3e39c9c698fd9c4e69f291ecce2
25039f952de3cc6dfc1e7bc1d89f0c464d772b79
68f71cdda2456d34b008855a2ec85d5954e098a0

with this changes `@latest` releases will use _mjCV5Dc4VAKXLJAH5g7LyHyW1jrIR3to_ and `@next` _sFdziRVDJo0taOnGzTZwafEL9nLIANZ3_

For dev, we should disable analytics or change `.dclinfo` JSON "segmentKey" property.

**Comment by dnul** [comment]
> Change default env segment_key to **mjCV5Dc4VAKXLJAH5g7LyHyW1jrIR3to.**
> 
> only set **sFdziRVDJo0taOnGzTZwafEL9nLIANZ3** for releases.

`with this changes @latest releases will use mjCV5Dc4VAKXLJAH5g7LyHyW1jrIR3to and @next sFdziRVDJo0taOnGzTZwafEL9nLIANZ3
`
Isn't it the other way around??
@latest == release versions right?
