### ISSUE TITLE
Fix duplication of files at building

### ISSUE THREAD

**Issue by fmiras** [decentraland/cli#368]
# What? 
When using `npm run cli:build` or `npm run cli:watch` scripts the ncc static evaluator or mod resolving is also duplicating all the `lib` folder from `src` to `dist`. We should either delete it after building or change ncc configuration to stop doing that, same with assets such as `certs` or `css`.

# Why? 
Avoid adding extra files to the build and get a smaller install size npm package.

**Comment by lyricalpolymath** [comment]
I'm not sure if this is connected, but if you change the scene.json file while the preview is running, then all entities on scene are duplicated
steps to reproduce the bug
1 - launch a scene with some items 
2 - while the preview is running, edit the scene.json base position to even 1 block away 
(from [0,0] to [0,1])

you should see all the previous generated items still in the scene
