### ISSUE TITLE
feat: change ECS sample now deploy

### ISSUE THREAD

**Issue by fmiras** [decentraland/cli#370]
# What? 
Create a `now.json` instead of using `npm run deploy:now`

# Why? 
Users should debug and use the `now-cli` experience

**Comment by menduz** [comment]
`dcl init-now` to create the files maybe? along with the Dockerfile?

**Comment by fmiras** [comment]
@menduz maybe create a boilerplate `ecs-now` and put it as default? I think is better to have extra files (and put them into `.dclignore`) instead of missing files at the time of generating the project

**Comment by menduz** [comment]
what if the somebody has a scene working and they suddenly wants to use now? does they require to initialize a new boilerplate?

**Comment by eordano** [comment]
I don't think it's a good default -- I like @menduz's idea of a command to generate it... I don't like having too many extra boilerplate files by default...

**Comment by fmiras** [comment]
We don't need this anymore since we have `dcl export` command and now 2 support
