### ISSUE TITLE
Suggest building project when deploy failed

### ISSUE THREAD

**Issue by fmiras** [decentraland/cli#373]
# What? 
Sometimes users try to `dcl deploy` before building since they do it before even running `dcl start` for the first time (which it runs `npm run build` for us). We should suggest running `npm run build` in case the reason of deploy failure is that `game.js` file is missing
 
# Why? 
So users get to know how to solve this issue.

**Comment by matiasbargas** [comment]
What do you think about building automatically before every deploy? probably only if the `build` folder/asset doesn't exist. Same behavior with `npm install` before a `start` if `node_modules` is not there.

**Comment by menduz** [comment]
what if we add a "predeploy" script to the npm package and set it to "npm run build" by default? a-la npm
