### ISSUE TITLE
dcl start throws errors for ecs scenes in builds after 2.1.0-20190117174453.commit-68f71cd

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#374]
--- environment
Windows 10, Chrome

---- The following works --------
npm i -g decentraland@2.1.0-20190117174453.commit-68f71cd
dcl init
dcl start

----- If I use 2.2.0, 2.2.1 or 2.2.2 I get the following:
dcl init
dcl start
√ Installing dependencies

> dcl-project@1.0.0 watch C:\Users\cfrav\webvr\DCL\ECS-boilerplate-2019-01-21
> build-ecs --watch

'build-ecs' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dcl-project@1.0.0 watch: `build-ecs --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dcl-project@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cfrav\AppData\Roaming\npm-cache\_logs\2019-01-22T05_45_13_000Z-debug.log
Error: `dcl start` Main scene file bin/game.js is missing, run "dcl help start" for more info.

**Comment by fmiras** [comment]
Please @cfravel check again, I see in this output that you're executing `dcl init` and `dcl start` before the dependencies get installed. It should be:
```bash
dcl init
√ Installing dependencies
dcl start
```
And not:

```bash
dcl init
dcl start
√ Installing dependencies
```

**Comment by cfravel** [comment]
i will retest tonight.
I doubt that I could be doing dcl start before the dependencies are installed, because I don't get the command line cursor back.
I just didn't put it in the report.

**Comment by menduz** [comment]
We have a hint about the issue, we will post an update soon, Thanks

**Comment by cfravel** [comment]
Did a clean install on another laptop today
Got the same error

C:\Users\cfravel>npm i -g decentraland
C:\Users\cfravel\AppData\Roaming\npm\dcl -> C:\Users\cfravel\AppData\Roaming\npm\node_modules\decentraland\bin\dcl
+ decentraland@2.2.2
added 1 package in 1.369s

C:\Users\cfravel>md webvr

C:\Users\cfravel>cd webvr

C:\Users\cfravel\webvr>md DCL

C:\Users\cfravel\webvr>cd DCL

C:\Users\cfravel\webvr\DCL>md SDK-2.2.2-test-ecs

C:\Users\cfravel\webvr\DCL>cd SDK-2.2.2-test-ecs

C:\Users\cfravel\webvr\DCL\SDK-2.2.2-test-ecs>dcl version
2.2.2

C:\Users\cfravel\webvr\DCL\SDK-2.2.2-test-ecs>dcl init
? Send anonymous usage stats to Decentraland? Yes
√ Dependencies installed

Success! Run 'dcl start' to see your scene


C:\Users\cfravel\webvr\DCL\SDK-2.2.2-test-ecs>dcl start
√ Installing dependencies

> dcl-project@1.0.0 watch C:\Users\cfravel\webvr\DCL\SDK-2.2.2-test-ecs
> build-ecs --watch

'build-ecs' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dcl-project@1.0.0 watch: `build-ecs --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dcl-project@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cfravel\AppData\Roaming\npm-cache\_logs\2019-01-22T23_17_18_167Z-debug.log
Error: `dcl start` Main scene file bin/game.js is missing, run "dcl help start" for more info.

**Comment by cfravel** [comment]
WORKAROUND

I have confirmed that if you run "npm install"  when in your scene directory, before running "dcl start" the dcl start will work without throwing those errors
