### ISSUE TITLE
Please support tiling of textures on primitives. 

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#375]
Scenario:
1. Large plot of parcels
2. Want to put a tileable texture (like a good grass or brick surface) on the ground by putting a texture on a PlaneShape or a BoxShape. Maybe that shape is even several parcels by several parcels.
3. In A-Frame I can specify tiling (how many repeats of the texture in each direction.
4. In SDK the texture always is tiled once on the primitive, regardless of the primitive's size

Tileable grass in A-Frame:
![image](https://user-images.githubusercontent.com/21015643/51517250-d0d45680-1ddf-11e9-9019-10b40fd91b51.png)

Same texture (not tiled) in SDK:
![image](https://user-images.githubusercontent.com/21015643/51517159-8e127e80-1ddf-11e9-8e22-eacca47a0a20.png)

**Comment by menduz** [comment]
You can do it by setting the UVs of the plane
