### ISSUE TITLE
Command not found (dcl init)

### ISSUE THREAD

**Issue by cesar9418** [decentraland/cli#381]
I used npm install -g decentraland
![decentraland instalar](https://user-images.githubusercontent.com/47048783/51811633-76217b80-2273-11e9-8b97-298e0893f86d.PNG)

_Originally posted by @cesar9418 in https://github.com/decentraland/cli/issues/61#issuecomment-457982173_

**Comment by menduz** [comment]
What is the problem? That image suggests that the installation succeed. Try executing `dcl help` now.

**Comment by cesar9418** [comment]
The problem is that i cannot use the command dcl.
If i write =  dcl init, appears: (Command not found)

**Comment by cesar9418** [comment]
Any command with dcl, appears  (Command not found)

**Comment by fmiras** [comment]
@cesar9418 please show us some more info:

- Operating System
- npm & node version

Try also executing dcl directly with `npm dcl <command>` e.g. `npx dcl help`

**Comment by cesar9418** [comment]
Opertaing System:MacOS Mojave  Version 10.14 
Npm 6.5.0
node version 11.7.0

Also the comand npm dcl init or any with dcl is not avaiable 

If you can help me I would appreciate it

![npm comand](https://user-images.githubusercontent.com/47048783/51854225-ecfc5a00-22ef-11e9-9f0f-59c5e78551c2.PNG)

**Comment by fmiras** [comment]
@cesar9418 try `npx` instead of `npm` they are different commands (with your installed version of npm you should already have npx)

**Comment by menduz** [comment]
ok, you are typing it wrong

You do
```
npm dcl start
```

This is the correct way
```
dcl start
```

**Comment by cesar9418** [comment]
With npx dcl init, everithyng was ok. But when i tried  to start the project with npx dcl start (command not found).   Something happens that suddenly that the coamnd npx dcl ( init or star), was not found.

I aslo tried with dcl start.

We are near to solve this

![npx dcl start](https://user-images.githubusercontent.com/47048783/51858199-bdeae600-22f9-11e9-86b3-e939eeb129d8.PNG)

**Comment by fmiras** [comment]
@cesar9418 You should `npx decentraland <command>` since the npm package have that name, for example:

```bash
npx decentraland help
npx decentraland init
npx decentraland start
```

This does not completely solve the issue of course, but the root problem is your npm global installation configuration, you can try installing globally any other npm package to re-confirm that

**Comment by cesar9418** [comment]
I can adavance with npx decentraland start but now i have this message

![npx decentraland start](https://user-images.githubusercontent.com/47048783/51861466-f098dc80-2301-11e9-8752-865db359f522.PNG)

**Comment by cesar9418** [comment]
No internet conection is the problem, thanks for all your help @fmiras , if you can help me with this i will be very very glad

**Comment by cesar9418** [comment]
It happens the same problem (no internet connection) @fmiras 
![no internet](https://user-images.githubusercontent.com/47048783/51866810-8a1abb00-230f-11e9-8fb8-87a8683e03dc.PNG)

**Comment by fmiras** [comment]
There is clearly a problem with your `npm` command because it doesn't even install the packages listed at `package.json`. Maybe you should contact npm support or search on npm repository for issues like yours
