### ISSUE TITLE
With npx dcl init, everithyng was ok. But when i tried  to start the project with npx dcl start (command not found).   Something happens that suddenly that the coamnd npx dcl ( init or star), was not found.

### ISSUE THREAD

**Issue by cesar9418** [decentraland/cli#384]
With npx dcl init, everithyng was ok. But when i tried  to start the project with npx dcl start (command not found).   Something happens that suddenly that the coamnd npx dcl ( init or star), was not found.

I aslo tried with dcl start.

We are near to solve this

![npx dcl start](https://user-images.githubusercontent.com/47048783/51858199-bdeae600-22f9-11e9-86b3-e939eeb129d8.PNG)

_Originally posted by @cesar9418 in https://github.com/decentraland/cli/issues/381#issuecomment-458250799_

**Comment by fmiras** [comment]
Please let's trace this back to the original issue. This is not a bug since our npm package isn't named `dcl` but `decentraland`

**Comment by matiasbargas** [comment]
Hi @cesar9418, You are mixing the names, you need to install `decentraland` package globally and then run `dcl start` without npm or npx.
