### ISSUE TITLE
The default ECS scene uses .set() instead of .add()

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/cli#386]
The example scene created with the CLI, uses .set() to add all the components.  In all of the examples in the docs, sample scenes and blogposts, we use .add() by default, and only use .set() when it's needed to have replaceable components.

It's a small difference, but it's the very first code you see when you use the ECS for the first time. It should be consistent with all the other reference material so that it's easy to understand for a newbie.

**Comment by matiasbargas** [comment]
Blocked by client/#546

**Comment by nearnshaw** [comment]
I wouldn't say it's totally blocked by [decentraland/client#546](https://github.com/decentraland/client/issues/546), especially if we want to release the CLI soon and the SDK in about a month.

There's be some rework, but it's a very minor change

**Comment by fmiras** [comment]
I just separated issues. Refer to #400
