### ISSUE TITLE
`dcl` should not open the interactive console

### ISSUE THREAD

**Issue by eordano** [decentraland/cli#4]
The interactive console is probably not going to be very useful until some point in the future. Let's hide that and make "help" the default command.

**Comment by NicoSantangelo** [comment]
It looks like this goes against [vorpal](https://github.com/dthree/vorpal) design choices, as stated [here](https://github.com/dthree/vorpal/wiki/FAQ#what-is-an-immersive-cli-app), but it's easy to avoid.

@michaltakac @eordano do we have a command name for entering `immersive mode` if it's not via `dcl` ? Using cli as a command, as in `dcl cli`, is confusing

**Comment by NicoSantangelo** [comment]
For what I can see, the best approach is to avoid having a `interactive` mode.

**Comment by michaltakac** [comment]
Right now we don't need the interactive feature but it's a nice-to-have for future stuff we'll be doing.  To not use interactive mode by running `dcl` but instead show help can be easily done by doing this:

```javascript
if (process.argv.length > 2) {
  vorpal.parse(process.argv);
} else {
  // Enters immersive mode if no commands supplied
  vorpal.log(`Decentraland CLI v${VERSION}\n`);
  vorpal.exec('help').then(() => vorpal.exec('exit'));
}
```
