### ISSUE TITLE
Raise deploy file limits

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/cli#418]
Today the CLI doesn't allow you to deploy scenes with more than 100 files, no matter the size of the scene.

This number sounds high, bug most of the winning scenes of the Builder contest have more than 100 files, from all the 3D models they use. Since many are large scenes with a lot of parcels, they are ok with the triangle and MB limitations, but not the max files limit.

This limit should ideally be proportional to the amount of parcels being used. We need to come up with numbers.

Until we do, can we raise this limit, at least to 300?

**Comment by fmiras** [comment]
Fixed 30bbf274a0090c195604a19a68491bccef23233e
