### ISSUE TITLE
Deployment Authorization not working

### ISSUE THREAD

**Issue by fmiras** [decentraland/cli#422]
# What? 
`dcl deploy` not working correctly, even being an owner of the parcel the linker app is telling that the developer hasn't got permissions

**Comment by fmiras** [comment]
Mistaken

**Comment by nearnshaw** [comment]
@fmiras  what was the mistake? Is there a workaround?

I was able to deploy scenes yesterday, but last night I installed the @next version of the CLI and today I can't deploy to the same parcels as before. I tried with a couple of different scenes, and they all say this:

✖ Failed to upload content
Error: `dcl deploy` Unable ro upload content. address is not authorized to modify given parcels, run "dcl help deploy" for more info.
