### ISSUE TITLE
Preview always starts in [0,0] , even if scene is far away

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/cli#435]
When I run `dcl start`, the preview always starts in 0,0

If the scene.json has coordinates set to any other location, like [65, -70], then I need to manually set that position on the URL in the browser.

This problem is new since we made Unity the default, it didn't happen with Babylon.

**Comment by belohlavek** [comment]
<img width="674" alt="Screen Shot 2019-06-13 at 10 13 08" src="https://user-images.githubusercontent.com/1307029/59435440-f8927e00-8dc3-11e9-8158-b5830478466a.png">
