### ISSUE TITLE
Deployed files are renamed to lower case

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/cli#456]
Reported by Carl Fravel, needs investigating:

the new SDK changes path names and filenames to all lower case before trying to load them, and therefor fails.
It started happening fairly recently.
if I change all my old directories and filenames to lower case the scene works again.
I think this is a bug, shouldn't lowercase the strings, it should use them as they are in the code.

**Comment by menduz** [comment]
Decentraland have a case insensitive virtual file system, therefore all files must be normalized in casing. To do so MUST be lower case and MUST be loaded using lower case.

**Comment by nearnshaw** [comment]
Taking issue over to the Unity Client, thanks
