### ISSUE TITLE
Change the TeleportPosition field for a series of Spawn Points

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/cli#457]
We want to change the single TeleportPosition field that's now in the scene.json into something that supports multiple spawn points.

This is the proposed new syntax for setting that:

```
{ ...

"spawnPoints": [
    {
      "name": "defaultSpawn",
      "position": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "camera": {
        "x": 0,
        "y": 0,
        "z": 0,
        "w": 0
      },
      "default": true
    }
  ],

...}
```

This effort will need to be coordinated with the world team, so that the feature ships on both sides at the same time

**Comment by nchamo** [comment]
@nearnshaw , closing this since it looks like it was already implemented. Please re-open if I misunderstood
