### ISSUE TITLE
Land data is not updated after doing `land.updateManyLandData`

### ISSUE THREAD

**Issue by cazala** [decentraland/cli#46]
So I deployed a parcel in ropsten (200, 200), I transfered it to my metamask address, and I authorized myself as an operator (which should allow me to update that parcels data using updateManyLandData according to the LANDRegistry contract).

I created a new project `dcl init` and I pushed it `dcl push`. It uploaded it to IPFS, it updated IPNS and then I was prompted to link the project to ethereum. I sent the transaction, sending the right `x` and `y` and the IPNS hash as the data (I console.log'd it to verify), it did go thru successfully ([here](https://ropsten.etherscan.io/tx/0xc4dde29c3c9dbfef3783955f146b4e6630abb427c92d2a3b1699ebce49fca001)) so finally I went to truffle, connected to ropsten and did a `landData` of my parcel, and it return `""` :( 

So from the CLI it looks like everything is working, but then I can't retrieve the IPNS hash using the contract... idk if it's an issue with `updateManyLandData` when writing or with `landData` when reading.

Any ideas?

**Comment by abarmat** [comment]
Let's try the whole path with the new contracts and try to reproduce the problem.

**Comment by abarmat** [comment]
Now it works!
