### ISSUE TITLE
CLI installation issues

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/cli#464]
This was reported by SpiderMonkey, who tried to install the CLI following the instructions in the docs

![Screen Shot 2019-08-01 at 11 27 02](https://user-images.githubusercontent.com/3507907/62301710-74698800-b44f-11e9-9043-1601922dd843.png)
![Screen Shot 2019-08-01 at 11 26 41](https://user-images.githubusercontent.com/3507907/62301720-7895a580-b44f-11e9-9394-cb4e7df73078.png)

**Comment by fmiras** [comment]
This is very poor data, I'm going to close it and reopen it in case there are more conditions, it seems to be an NPM problem of the host machine and not of the package itself
