### ISSUE TITLE
Bug deploying: new BigNumber() not a base 16 number

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/cli#465]
Several people, me included, have had this bug when trying to deploy: 

new BigNumber() not a base 16 number

I don't know of any pattern for when it happens. In my case, it happens when trying to deploy some scenes, not others.

If I do this `export DCL_PRIVATE_KEY=<your wallet priv. Key>` ,  I can deploy those same scenes, so it seems not to be related to the scene's content.

At least the error message should say something clear and actionable in these cases.

**Comment by abarmat** [comment]
I will help trying to reproduce this problem @fmiras
