### ISSUE TITLE
Expand .dclignore to include some common formats that tend to cause issues.

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/cli#466]
Carl Fravel suggests using this list of files in the default .dclignore

Not sure if all of them are relevant enough, but def several could be included. A lot of people seem to have issues when trying to deploy with some of these file types.

package.json
package-lock.json
yarn-lock.json
build.json
export
tsconfig.json
tslint.json
node_modules
*.ts
*.tsx
Dockerfile
dist
README.md
now.json
vesta/
*.bat
scene-export.json
scene-deploy.json
*.blend
*.fbx
*.zip
*.rar

**Comment by nchamo** [comment]
Done in https://github.com/decentraland/cli/pull/512
@nearnshaw , let me know if you need to add more
