### ISSUE TITLE
Deploy Opens Metamask, but after signing spins forever

### ISSUE THREAD

**Issue by tpitman** [decentraland/cli#494]
# What?
dcl deploy
browser (chrome) opens to local page
click on deploy and sign button
Metamask opens
Login
see metamask page to cancel or sign with the same ID on the web page
click sign button
metamask window shows spinner
continues to spin for 30 minutes
close the window because I gave up

**Comment by armandojarm16** [comment]
Same happened to me, how did you solve that out?

**Comment by tpitman** [comment]
It turns out it was waiting for me to hit the ok or cancel on the actual Ledger device. I just didn't see it was waiting. As soon as I ok it it moves on and works.

**Comment by nchamo** [comment]
Closing do to inactivity. Please let me know if it happens again
