### ISSUE TITLE
DCL export metamask login broken

### ISSUE THREAD

**Issue by julesGoullee** [decentraland/cli#520]
When running local dev server with dcl start work properly. When exported with dcl export and serve statically (even on local), metamask login popup never open, in the browser console got the error `rejected due to project ID settings`

**Comment by nchamo** [comment]
Hey @julesGoullee !

We made a fix in both https://github.com/decentraland/explorer/pull/1270 and https://github.com/decentraland/cli/pull/521. So if you update both the CLI (`npm i -g decentraland@next`) and the SDK (`npm i decentraland-ecs@next`) it should work the same as `dcl start`.

That means, that you will still need to add the `ENABLE_WEB3` query parameter

**Comment by nchamo** [comment]
Please let us know if it happens again :)
