### ISSUE TITLE
Add .git to .dclignore by default

### ISSUE THREAD

**Issue by pabloes** [decentraland/cli#545]
dcl deploy scans files in working folder including ".git" folder in case your scene code is a git repository.

I request to add .git in .dclignore file by default

**Comment by nchamo** [comment]
@pabloes , feel free to create a PR for it!

The change should be done [here](https://github.com/decentraland/cli/blob/6b1fc13aa64e43adf8084242b585a9337ee5a285/src/lib/Project.ts#L219)

**Comment by pabloes** [comment]
It's already covered in last version with ".*", my fault.
