### ISSUE TITLE
[bug] `dcl export` fails with error code 

### ISSUE THREAD

**Issue by JollyGrin** [decentraland/cli#589]
# What? 
I cannot export my DCL scene. I'm able to use it without issue running `dcl start` but when I run `dcl export` i get the following:

```
✔ Build found
⠏ Exporting projectExport failed. Error: connect ECONNREFUSED 104.19.216.110:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '104.19.216.110',
  port: 443
}
Error: `dcl export` connect ECONNREFUSED 104.19.216.110:443, run "dcl help export" for more info.
```

# Why? 

I'm using WSL2.0 (not sure if that has anything to do with it)? Am I not supposed to use port 443 (even though that's the default?)

**Comment by leanmendoza** [comment]
Hi @JollyGrin! Could you try to test the `dcl export` installing decentraland-ecs@next?
Here the steps to update:
1. Go to the scene folder in a terminal
2. Run `npm i decentraland-ecs@next`
3. Try to run `dcl export`

**Comment by JollyGrin** [comment]
Thank you for your quick response @leanmendoza! 

So I tried your solution by first deleting node modules and then running your step 2. I received the following error
```
$ dcl export
✔ Build found
⠴ Exporting projectCouldn't fetch base avatars to serve statically. Please verify your internet connection
Export failed. Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:683:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1583:19)
    at TLSSocket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET',
  path: null,
  host: 'peer-eu1.decentraland.org',
  port: 443,
  localAddress: undefined
}
Error: `dcl export` Client network socket disconnected before secure TLS connection was established, run "dcl help export" for more info.
```

When I ran it again, I got:
```
$ dcl export
✔ Build found
⠋ Exporting projectCouldn't fetch base avatars to serve statically. Please verify your internet connection
Export failed. Error: connect ECONNREFUSED 104.19.217.110:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '104.19.217.110',
  port: 443
}
Error: `dcl export` connect ECONNREFUSED 104.19.217.110:443, run "dcl help export" for more info.
```

I'm not currently on a vpn, but my folder structure does include some cache files which is used as dependencies in the game.ts. I downloaded this from the browser builder. Is this typical?

![image](https://user-images.githubusercontent.com/28109194/135132169-01e12874-3285-4343-b61e-b02fc605d2be.png)

**Comment by gonpombo8** [comment]
dcl export is deprecated
