### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by diegodorado** [decentraland/cli#59]
cli doesn't seem to support a-entity objects, although it is listed as supported here:
https://wiki.decentraland.org/index.php?title=A-Minus#Supported_entities

sample scene:
```
<a-scene>
      <a-entity position='5 0 0' rotation='0 90 0'>
        <a-box color='#ff00aa' position='-2 0 0' />
        <a-box color='#00aaff' position='2 0 0' />
      </a-entity>
    </a-scene>
```

**Comment by diegodorado** [comment]
removing the `a-entity` makes it work:

sample scene:
```
    <a-scene>
        <a-box color='#ff00aa' position='-2 0 0' />
        <a-box color='#00aaff' position='2 0 0' />
    </a-scene>
```

**Comment by yanis7774** [comment]
same problem. also a-plane not working

**Comment by bnolan** [comment]
These problems are fixed in the newer version of preview.js. I'll create a PR to update to the latest version of the client.

<img width="777" alt="screen shot 2018-02-28 at 10 19 26 am" src="https://user-images.githubusercontent.com/17499/36755391-e6dffe00-1c70-11e8-9778-9154e047d9ef.png">

**Comment by yanis7774** [comment]
Thanks God!  One month passed
