### ISSUE TITLE
Cannot load obj file: Uncaught SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by diegodorado** [decentraland/cli#60]
With this sample scene:
```
    <a-scene>
      <a-obj-model src="./models/tree.obj" color='#00ffaa' scale='4 4 4' />
    </a-scene>

```

It seems to me some kind of typo in this blob script
```javascript

/**
  * This code was constructed by OBJLoader2 buildCode.
  */

Validator = {
	isValid: function (t){return null!==t&&void 0!==t},
	verifyInput: function (t,e){return null===t||void 0===t?e:t},
}

ConsoleLogger = (funcConsoleLoggerion () {

	function t(t,e){this.enabled=!1!==t,this.debug=!0===e}
```

but since it is autogenerated, i believe that some text replacement is not working well: look at `funcConsoleLoggerion` ... i would say that the `t` of function has been replaced by `ConsoleLogger`

**Comment by HAZARDU5** [comment]
I'm having the same issue - this prevents OBJ models from loading in the client currently.

**Comment by yanis7774** [comment]
Same

**Comment by bnolan** [comment]
This is fixed on PR #72.

<img width="1264" alt="screen shot 2018-02-28 at 11 16 41 am 2" src="https://user-images.githubusercontent.com/17499/36759540-932d78a8-1c7c-11e8-9fc1-613f0c0cbd7a.png">

The documentation may need updating - this is how I got the obj working:

```
      <a-obj-model obj-model="obj: models/rounded-cube.obj; mtl: models/rounded-cube.mtl"></a-obj-model>
```

**Comment by diegodorado** [comment]
I dont understand @bnolan Is it merged already with master branch?
I see preview.js in master branch is about a month old

**Comment by yanis7774** [comment]
@bnolan  guys,  more feedback please. We want to be inside

**Comment by rushughes** [comment]
[Test.zip](https://github.com/decentraland/cli/files/1770571/Test.zip)

Nothing shows with 
`      <a-obj-model
      obj-model="obj: models/HelloTestPink.obj; mtl: models/HelloTestPink.mtl;"
      position="0 0 0"
      rotation="0 0 0"
      scale="0.5 0.5 0.5"
      ></a-obj-model>
`

if i remove the mtl it works fine tho

`      <a-obj-model
      obj-model="obj: models/HelloTestPink.obj;"
      position="0 0 0"
      rotation="0 0 0"
      scale="0.5 0.5 0.5"
      ></a-obj-model>
`

this happens with everything we are exporting from 3dsmax

**Comment by rushughes** [comment]
looks like my issue relates to this https://github.com/syoyo/tinyobjloader/issues/43

Tr was set to 0.0000

id like to petition the behaviour of decentraland to be changed to match the behaviour of aframe

**Comment by HAZARDU5** [comment]
I'm not terribly familiar with how 3DSMax exports it's OBJs - what material settings did you have in there that caused Tr to be set to  0.0000?

**Comment by bnolan** [comment]
These issues are relevant to the client, we import the renderer into the CLI. I've logged an issue in the client and will close this one.
