### ISSUE TITLE
Problems with 'dcl start'

### ISSUE THREAD

**Issue by CommonN** [decentraland/cli#606]
[HPM] Error occurred while proxying request 192.168.101.2:8000/lambdas/profiles?id=0x7a686d2ad095818ca4259a794ee0d7c216fc24e2 to https://peer-lb.decentraland.org/ [ETIMEDOUT] (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while proxying request 192.168.101.2:8000/lambdas/contracts/pois to https://peer-lb.decentraland.org/ [ETIMEDOUT] (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while proxying request 192.168.101.2:8000/lambdas/profiles?id=default18 to https://peer-lb.decentraland.org/ [ETIMEDOUT] (https://nodejs.org/api/errors.html#errors_common_system_errors)
Acquiring comms connection.
[HPM] Error occurred while proxying request 192.168.101.2:8000/lambdas/profiles?id=0x7a686d2ad095818ca4259a794ee0d7c216fc24e2 to https://peer-lb.decentraland.org/ [ETIMEDOUT] (https://nodejs.org/api/errors.html#errors_common_system_errors)

![image](https://user-images.githubusercontent.com/38940157/143688702-26a8462f-dd90-4779-a991-bf2508a5afdb.png)

**Comment by CommonN** [comment]
I don't understand why？

**Comment by CommonN** [comment]
![image](https://user-images.githubusercontent.com/38940157/143688987-11168f4a-c7b2-4991-b604-d49dc2106617.png)




is not what I want！！！！！！！！！！

**Comment by CodeJuggernaut** [comment]
I'm also seeing this same error.

**Comment by yanis7774** [comment]
Same things happen periodically

![Снимок экрана 2022-01-20 в 12 51 47](https://user-images.githubusercontent.com/34626980/150315252-0dbdd2f4-994d-4be1-8a7a-ad4317c26ec7.png)


A few users on sdk channel also reported this.

**Comment by gonpombo8** [comment]
Fixed at decentraland@latest.
try `npm i -g decentraland@latest`
