### ISSUE TITLE
Error with Upload

### ISSUE THREAD

**Issue by yanis7774** [decentraland/cli#61]
Hi! 

I installed 0.2.9 v. and I cant to start dcl upload. in 2.7 it was worked. 

there is log: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start', 'upload' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle decentraland@0.2.9~prestart: decentraland@0.2.9
6 info lifecycle decentraland@0.2.9~start: decentraland@0.2.9
7 verbose lifecycle decentraland@0.2.9~start: unsafe-perm in lifecycle true
8 verbose lifecycle decentraland@0.2.9~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/hsbs/Documents/GitHub/cli/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/hsbs/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
9 verbose lifecycle decentraland@0.2.9~start: CWD: /Users/hsbs/Documents/GitHub/cli
10 silly lifecycle decentraland@0.2.9~start: Args: [ '-c', './dev.js "upload"' ]
11 silly lifecycle decentraland@0.2.9~start: Returned: code: 1  signal: null
12 info lifecycle decentraland@0.2.9~start: Failed to exec start script
13 verbose stack Error: decentraland@0.2.9 start: `./dev.js "upload"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid decentraland@0.2.9
15 verbose cwd /Users/hsbs/Documents/GitHub/cli
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "upload"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error decentraland@0.2.9 start: `./dev.js "upload"`
22 error Exit status 1
23 error Failed at the decentraland@0.2.9 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

MacBook-Pro-2:cli hsbs$ npm start upload

> decentraland@0.2.9 start /Users/hsbs/Documents/GitHub/cli
> ./dev.js "upload"

You're now in development mode.
Could not find `.decentraland/project.json`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! decentraland@0.2.9 start: `./dev.js "upload"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the decentraland@0.2.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hsbs/.npm/_logs/2018-02-02T06_47_27_120Z-debug.log
MacBook-Pro-2:cli hsbs$

**Comment by cazala** [comment]
Hi @yanis7774, can you try to re-init the project? we added a `.decentraland/project.json` that was not present on the previous versions. 

You can backup you `scene.html` and `scene.json` files, run `dcl init` on a new directory, after inited you can replace the `scene.html` and `scene.json` with the old ones.

```
$ mkdir new-dcl-project
$ cd new-dcl-project
$ dcl init
$ cp ../old-dcl-project/scene.html .
$ cp ../old-dcl-project/scene.json .
```

If you have already linked your project to ethereum, and you want to keep using that link, you can do the following:

Get the old project's IPNS hash:

```
$ cat old-dcl-project/.decentraland/ipn
```
It will print something like this:

```
QmQDzugiJPv5XrrHKXhJA6KK1BBdW5RKYQ4e6mUrxEyYoS
```

then edit the new project's `project.json`:

```
$ vi new-dcl-project/.decentraland/project.json
```

It will look like this:

```json
{
  "id": "2584e15c-0d44-446b-9b73-6a953fe851bb",
  "ipfsKey": null
}
```

Paste the old project's IPNS hash as the new project's IPFS key:

```
{
  "id": "2584e15c-0d44-446b-9b73-6a953fe851bb",
  "ipfsKey": "QmQDzugiJPv5XrrHKXhJA6KK1BBdW5RKYQ4e6mUrxEyYoS"
}
```

Now your next `dcl upload` will publish your content to the same IPNS link as before, otherwise it will generate a new one and you will have to do `dcl link` one more time to update the blockchain with this new link.

The reason behind this change was that the old version of the CLI wasn't able to create more than IPNS link... so if you created a second project, it would use the same link as the first one, overriding its connect once you did `dcl upload`. After `v0.2.9` each project has its own IPFS key and generates its own IPNS link.

**Comment by yanis7774** [comment]
HI! @cazala 

Yes I tried to do it. But i run it by "npm start init" because dcl init isnt working for me. 
So.. I init a new scene, but there is the same situation. 
.decentraland/project.json - cant to see the folder after init.

**Comment by cazala** [comment]
If you init a new project from scratch on an empty directory you get that error? what error do you get when you do dcl init?

**Comment by yanis7774** [comment]
@cazala 
I tried to install new one. See the log. 

MacBook-Pro-2:cli hsbs$ npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> decentraland@0.2.9 prepublish /Users/hsbs/Documents/GitHub/cli
> npm run build


> decentraland@0.2.9 build /Users/hsbs/Documents/GitHub/cli
> npm run clean && tsc && npm run linker:build


> decentraland@0.2.9 clean /Users/hsbs/Documents/GitHub/cli
> rimraf dist && rimraf tmp


> decentraland@0.2.9 linker:build /Users/hsbs/Documents/GitHub/cli
> next build && next export -o dist/linker-app

> Using external babel configuration
> Location: "/Users/hsbs/Documents/GitHub/cli/.babelrc"
> Using "webpack" config function defined in next.config.js.
  using build directory: /Users/hsbs/Documents/GitHub/cli/.next
  copying "static" directory
  exporting path: /linker

up to date in 37.167s
MacBook-Pro-2:cli hsbs$ cd.. 
-bash: cd..: command not found
MacBook-Pro-2:cli hsbs$ cd ..
MacBook-Pro-2:github hsbs$ cd ..
MacBook-Pro-2:documents hsbs$ cd ..
MacBook-Pro-2:~ hsbs$ cd DCL
MacBook-Pro-2:DCL hsbs$ npm install -g decentraland
npm WARN deprecated validate-commit-msg@2.14.0: Check out CommitLint which provides the same functionality with a more user-focused experience.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated github@12.1.0: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
npm WARN deprecated @semantic-release/last-release-npm@2.0.2: Use @semantic-release/npm instead
npm WARN deprecated @semantic-release/condition-travis@6.2.1: Use semantic-release@12.0.0 instead
/Users/hsbs/.npm-global/bin/dcl -> /Users/hsbs/.npm-global/lib/node_modules/decentraland/bin/dcl

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/hsbs/.npm-global/lib/node_modules/decentraland/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

+ decentraland@0.2.9
updated 7 packages in 79.879s
MacBook-Pro-2:DCL hsbs$ npm link
npm WARN npm_package@1.0.0 No repository field.

up to date in 14.991s
/Users/hsbs/.npm-global/lib/node_modules/npm_package -> /Users/hsbs
MacBook-Pro-2:DCL hsbs$ dcl init
-bash: dcl: command not found
MacBook-Pro-2:DCL hsbs$

**Comment by yanis7774** [comment]
one more question, Can I run A-frame inspector on the scene in browser, when I run "dcl start"?

**Comment by yanis7774** [comment]
@cazala after few reinstall i got project.json 
About dcl init - i got that 

MacBook-Pro-2:cli hsbs$ dcl init
-bash: dcl: command not found

**Comment by cazala** [comment]
in order to be able to use `dcl init` (or any other `dcl <command>`) you have two options:

1) install it globally: `npm install -g decentraland@latest`

2) if you have cloned the repo (which I think is the case) you need to link it first: `npm link`, then you will be able to use the `dcl` command.

**Comment by yanis7774** [comment]
i did it for sure, but it`s still not working
Log: 

MacBook-Pro-2:cli hsbs$ npm link
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> decentraland@0.2.9 prepublish /Users/hsbs/Documents/GitHub/cli
> npm run build


> decentraland@0.2.9 build /Users/hsbs/Documents/GitHub/cli
> npm run clean && tsc && npm run linker:build


> decentraland@0.2.9 clean /Users/hsbs/Documents/GitHub/cli
> rimraf dist && rimraf tmp


> decentraland@0.2.9 linker:build /Users/hsbs/Documents/GitHub/cli
> next build && next export -o dist/linker-app

> Using external babel configuration
> Location: "/Users/hsbs/Documents/GitHub/cli/.babelrc"
> Using "webpack" config function defined in next.config.js.
  using build directory: /Users/hsbs/Documents/GitHub/cli/.next
  copying "static" directory
  exporting path: /linker

up to date in 40.533s
/Users/hsbs/.npm-global/bin/dcl -> /Users/hsbs/.npm-global/lib/node_modules/decentraland/bin/dcl
/Users/hsbs/.npm-global/lib/node_modules/decentraland -> /Users/hsbs/Documents/GitHub/cli
MacBook-Pro-2:cli hsbs$ dcl start
-bash: dcl: command not found
MacBook-Pro-2:cli hsbs$ dcl init
-bash: dcl: command not found
MacBook-Pro-2:cli hsbs$

**Comment by cesar9418** [comment]
Hi i am having the same problem, how you solve it?

**Comment by eordano** [comment]
It seems like the "dcl" command is not in your path. How did you installed npm?

**Comment by cesar9418** [comment]
I used npm install -g decentraland
![decentraland instalar](https://user-images.githubusercontent.com/47048783/51811633-76217b80-2273-11e9-8b97-298e0893f86d.PNG)

**Comment by cesar9418** [comment]
I also tried with this 
![npm install](https://user-images.githubusercontent.com/47048783/51812042-820e3d00-2275-11e9-84bc-0bdc24453f4f.PNG)

**Comment by DavidGR94** [comment]
Hi, currently I´m having the exact problem with that. I introduce after installation npm install -g decentraland the command "dcl init" but "command not found" appears. I have macOS last version.

**Comment by DavidGR94** [comment]
No that´s the first time I install this kind of package.  I will try to double check the steps in the #381 
as you said probably is a problem with the npm.
