### ISSUE TITLE
add 'update package' instructions to readme

### ISSUE THREAD

**Issue by yanis7774** [decentraland/cli#63]
Can you add in readme, How to correct update the package.

**Comment by kfarr** [comment]
Hi Yanis, can you be a bit clearer -- do you mean how to have an updated version of Node, Python, etc when starting to use this? What platform are you using - Windows or Linux/Mac?

**Comment by yanis7774** [comment]
Hi! I mean if new relise will come, how can i update it. MAC OS

**Comment by HAZARDU5** [comment]
@yanis7774 if you're on MacOS, just stick with the npm releases and install it globally with `npm install -g decentraland`. Then to update do `npm -g upgrade decentraland`

**Comment by bnolan** [comment]
This is [documented](https://github.com/decentraland/cli/blob/master/README.md#updating) in the readme now.
