### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by eordano** [decentraland/cli#64]
Remove the following warnings:

- [ ] `validate-commit-msg`: Use `CommitLint`
- [ ] `semantic-release`: Use `semantic-release/npm`
- [ ] `babel-preset-es2015`: A dependency is using this outdated package (preset `env` has an up-to-date ecmascript version).
- [ ] `github`: Use `octokit/rest`

**Comment by michaltakac** [comment]
`validate-commit-msg` and `semantic-release` are demendencies of `decentraland-commons` which we use in this project.

About the other two - have to find out which uses them.

**Comment by bnolan** [comment]
@eordano how are you generating that dependency warnings list? None of those are direct dependencies and we have updated to `babel-preset-env` already.
