### ISSUE TITLE
dcl init fails

### ISSUE THREAD

**Issue by prismspecs** [decentraland/cli#643]
dcl init returns "Error: `dcl init` Unexpected token ?, run "dcl help init" for more info."

node v10.19.0 on Ubuntu 20.04

**Comment by gunerguney** [comment]
I have the same problem with running `dcl init`

it returns `Error: dcl init Unexpected token '?', run "dcl help init" for more info.`

Ubuntu: 18.04
node: v12.14.1
npm: 6.13.6

![image](https://user-images.githubusercontent.com/5878041/155528310-30eb0aa3-e749-43b3-a198-0474f7143a8a.png)

**Comment by leanmendoza** [comment]
Thank for reporting, we'll be checking it. @decentraland/sdk-team

**Comment by juanigallo** [comment]
This is because `dcl init` uses optional chaining that was introduced in node `14.x.x`, to fix this issue just update your node version and you will be ok.

cc @leanmendoza @prismspecs @gunerguney

**Comment by leanmendoza** [comment]
Thanks @juanigallo !!

**Comment by gunerguney** [comment]
After updating the node version the problem was solved, thank you @juanigallo
