### ISSUE TITLE
import jimp on decetraland scene

### ISSUE THREAD

**Issue by happyit84** [decentraland/cli#658]
# What? 
On the Denetraland Scene, I'm trying to import Jimp(https://github.com/oliver-moran/jimp).
But dcl build fails.
To solve build error, I tried a lot of things but I am still stuck in that issue.

So I tried Jimp on clean typescript project. and I found possile reason why Jimp is not imported properly is:
Decentrand only allows AMD modules.
As you know default setting of tsconfig>compilerOptions.module is "commonjs".
but decentraland scene's tsconfig extends to tsconfig in "./node_modules/decentraland-ecs/types/tsconfig.json" and module is set to "amd".

So my question is: Can't decentraland scene load commonjs module(jimp is commonjs-base)? only allows import AMD module?

...

# Why? 

...

Thanks

**Comment by marcofugaro** [comment]
I agree, decetraland should add support for commonjs/esmodules, this is blocking so many libraries.

**Comment by menduz** [comment]
Decentraland's Runtime is neither the browser's or Node.js for the sake of portability and backwards compatibility, the exposed functions are limited and the size of the code of the scenes must be also limited. For those reasons, among others, like the lack of filesystem, commonjs/esm are not supported.
