### ISSUE TITLE
Pin scenes to decentraland ipfs node

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/cli#66]
## Motivation

As we are developing an own Decentraland IPFS node, we could pin created/updated scenes.

With this, we are not going to be dependent on the local user IPFS node to be up when getting the scene from our apps.

## Concept Implementation

I've worked in an [experimental branch](https://github.com/decentraland/cli/tree/connect-with-ipfs-node), only focused on functional things.

### We need to: 

- store the peerId of the local user IPFS node as [here](https://github.com/decentraland/cli/blob/connect-with-ipfs-node/src/utils/uploader.ts#L69)

- pin the files at Decentraland IPFS node once [update land data transaction is completed] (https://github.com/decentraland/cli/blob/connect-with-ipfs-node/pages/linker.js#L164) to be always available. [And when an update occurs](https://github.com/decentraland/cli/blob/connect-with-ipfs-node/src/utils/uploader.ts#L111)

- show the process [flow status](https://github.com/decentraland/cli/blob/connect-with-ipfs-node/pages/linker.js#L214) to the user (fully experimental)

### Endpoint (@ALPHA stage) 

```
@GET http://ipfs.decentraland.zone:3000/api/pin/:peerid/:x/:y

Response: { ok: 'true' } or {'ok': false}
```
- Needs https
- We can make it more verbose to handle errors better.

### Test

`npm start -- init`

Fill at least the parcels you own

#### Pin new scene

`npm start -- upload`

`npm start -- link`

#### Update Scene

 Make a change in your scene, then run:

`npm start -- upload`

To see them reflected you can use:

http://ipfs.decentraland.zone:3000/api/resolve/:ipns?dependencies=true

E.g: http://ipfs.decentraland.zone:3000/api/resolve/QmTZZnwcsUJuQL2EH3oLZBaA6HZvhv8KJ7Qd9QP9LpEjW1?dependencies=true

Thanks @menduz for the early catch.

**Comment by menduz** [comment]
Will the users be able to hit this endpoint?

**Comment by nachomazzara** [comment]
The main idea is to make it transparent to the users.

The only issue making this endpoint available for everyone (not only for Decentraland apps) is to prevent being the storage of the world. I mean, users could use that endpoint to host their own (non-related to Decentraland) files.

On the other hand, users could use our endpoint to get what is inside their IPNS (the scene)

Do you think we should need the _pin_ endpoint public?

**Comment by menduz** [comment]
I was talking about
> users could use that endpoint to host their own (non-related to Decentraland) files.

Any user could fullfil all of our storage. I would do that if I see the endpoint.

---

I see we are using `http` to call this service and sending the ipfs key. Please create an issue to upgrade to `https`

**Comment by nachomazzara** [comment]
Issue updated 💯
