### ISSUE TITLE
Support negative coordinates in npx @dcl/opscli pointer-consistency

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/cli#715]
The command `npx @dcl/opscli pointer-consistency` is used to verify that the content deployed to a certain parcel is the same on all catalyst servers.

This command can't read coordinates that start with a negative number in the X coordinate. You need to add a slash, which is unintuitive.

This doesnt' work:
`npx @dcl/opscli pointer-consistency --pointer '-115, -101'`

Returns the following error:
`code: ‘ARG_MISSING_REQUIRED_LONGARG’ `

This workaround does work:
`npx @dcl/opscli pointer-consistency --pointer '\-115, -101'`

Would be great to support the first case

**Comment by menduz** [comment]
The solution is `\-115,-101` instead of `-115,-101`
