### ISSUE TITLE
Update windows install instructions

### ISSUE THREAD

**Issue by bnolan** [decentraland/cli#78]
To recommend using https://github.com/felixrieseberg/windows-build-tools.

**Comment by HAZARDU5** [comment]
I've got a full set of working instructions here that I've tried against 2 dev machines. Both seem to be working:

---

If you have installed an older version of Visual Studio, please uninstall it before continuing as it may conflict with some of these command line tools. You can install the latest version of Visual Studio afterwards.

1. Install Node.js v8 LTS from https://nodejs.org/en/download/
2. Search Windows for *cmd.exe* and right click the *Command Prompt* app and select *Run as Administrator*
3. Install windows-build-tools: `npm install --global --production windows-build-tools`
4. Wait for both the Visual Studio Build Tools and Python installers to both read *Successfully installed xxxx*. When everything is done it will return you to the command prompt.
5. Download git (you'll likely want the 64-bit Windows version): https://git-scm.com/download/win
6. Install git and when prompted choose to install git bash
7. When prompted for a default text editor select *Use the Nano editor by default*
8. When prompted to adjust your path environment, select *Use Git from the Windows Command Prompt*
9. When prompted to choose the SSH executable, select *Use OpenSSH*
10. When prompted to choose the HTTPS transport backend, select *Use the OpenSSL library*
11. When prompted to configure the line ending conversions, select *Checkout Windows-style, commit Unix-style line endings*
12. When prompted to configure the terminal emulator to use with Git Bash select *Use MinTTY*
13. On the final installation screen select the following options: *Enable file system caching* and *Enable Git Credential Manager* and *Enable symbolic links*
14. Run `npm install -g decentraland`

Optional:
To get the latest bleeding edge version from github, follow these instructions in addition to the above:

1. Make a folder on your hard drive in a convenient location e.g. `c:\dcl`.
2. Open a Command Prompt and change directory to that location: e.g. `cd c:\dcl`
3. Run the following: `git clone https://github.com/decentraland/cli.git`
4. Run the following: `npm link`
5. In the future, to update to the latest version, follow step 2 to navigate to the git project, then run: `git pull`

**Comment by bnolan** [comment]
Thanks @HAZARDU5 , we've updated the documentation, but it might be good to merge your notes in, they're super detailed.

@cfravel what do you think?
