### ISSUE TITLE
Cannot load gltf model

### ISSUE THREAD

**Issue by HAZARDU5** [decentraland/cli#83]
While using `v0.3.1` of the CLI, I'm trying to load a gltf model using the following syntax:
```
<a-gltf-model src="models/damaged-helmet/DamagedHelmet.gltf" position="0 0 -2"></a-gltf-model>
```
I have my textures and model in the `models` folder of my cli project:
```
- DamagedHelmet.gltf
- DamagedHelmet.bin
- Default_albedo.jpg
- Default_AO.jpg
- Default_emissive.jpg
- Default_metalRoughness.jpg
- Default_normal.jpg
```

There aren't any JS console errors coming back and the model seems to load when inspecting the network tab (I get a 200 OK for DamagedHelmet.gltf). What doesn't seem to load is the `DamagedHelmet.bin` file which is required to load the full model geometry - a request for this file isn't event made by the client.

Source files are available here to test:

https://github.com/HAZARDU5/aframe-workshop/tree/master/examples/32/finish/assets/gltf/damaged-helmet

It's not showing in the client preview, however this same model works in A-Frame v0.7.1 as shown in the link below:

https://hazardu5.github.io/aframe-workshop/examples/32/finish/

**Comment by yanis7774** [comment]
Same problem. A-obj don't rendering also

**Comment by dafky2000** [comment]
It appears to be requesting the `.bin` file from a relative location causing it to request url to be http://127.0.0.1:2044/?position=-69%2C46Holy_Schau.bin

**Comment by dafky2000** [comment]
So if you initially load the scene at the root, http://127.0.0.1:2044/ and travel by foot to your parcel, the model is loaded because the initial load of the `.bin` file was successful. You need to edit the `.gltf` file in a text editor and look for:

```   "buffers" : [
       {
           "byteLength" : 40536,
           "uri" : "yourfilename.bin"
       }
   ],
```

and input the correct uri relative to the root directory

```   "buffers" : [
       {
           "byteLength" : 40536,
           "uri" : "models/yourfilename.bin"
       }
   ],
```

This is kind of a pain, when you make changes to your scene and live-reload kicks in, your model disappears and you need to travel there from root again.

**Comment by yanis7774** [comment]
@dafky2000 you can use http://127.0.0.1:2044/?position=-55%2C-41 (just change -55 and -41) And when you init a scene you can chose teleport position.

**Comment by yanis7774** [comment]
@dafky2000 i tried to change uri but glft still without textures. the car on the screenshot

What about obj? I can insert it, but mtl file isnt working
<img width="1438" alt="cli2" src="https://user-images.githubusercontent.com/34626980/37245362-6402fabc-24c9-11e8-9a6f-708eb9808c07.png">

**Comment by yanis7774** [comment]
@dafky2000 i don't go by walk

**Comment by dafky2000** [comment]
@HAZARDU5 I have tested this with your model and it seems to work - you will also need to change the path of the texture files.

![screenshot_2018-03-10_15-06-25](https://user-images.githubusercontent.com/2653187/37246280-a8f8cfde-2474-11e8-8801-d8a295c3569e.png)

**Comment by HAZARDU5** [comment]
Cool - I'll try this out tonight :-)

**Comment by HAZARDU5** [comment]
Yep works for me with the parcel changes. It only loads when viewed at `http://127.0.0.1:2044` in the web-browser. Other coordinates in the URL don't unfortunately (e.g. http://127.0.0.1:2044/?position=0%2C0)

@cazala are you able to provide a fix for this pathing issue in the client? URL variables just really need to be appended at the end of every request instead of being prepended.

**Comment by dafky2000** [comment]
The problem is that the `.bin` files are fetched via path relative to the current URL. They should be fetched relative to the `gltf` file path (but using the absolute path). Same as aframe does?

**Comment by HAZARDU5** [comment]
Looks like this is fixed in the `next` build of the CLI. You'll need to install it as follows to see the fix:

```
npm i -g decentraland@next
```
