### ISSUE TITLE
Z dimension

### ISSUE THREAD

**Issue by yanis7774** [decentraland/cli#84]
<img width="1439" alt="2018-03-08 16 08 27" src="https://user-images.githubusercontent.com/34626980/37143055-90ea2ba6-22ec-11e8-9660-bc7c68fd3d9a.png">
As I can see, there is Z dimension for a parcels in CLI. Does it mean that it is some limit for building in Z dimension?

**Comment by bnolan** [comment]
@menduz what is the current status of the z dimension height limit? Is it decided upon?
