### ISSUE TITLE
Technical infomations, limits, etc for bulding in CLI

### ISSUE THREAD

**Issue by yanis7774** [decentraland/cli#85]
Hey guys!

New version of CLI is working properly and we can start to build on our land. 
Could you give some tech information about limits (for .obj files for example), and other information that could be heplfull for working in CLI. 

Thanks.

**Comment by eordano** [comment]
Working on this. Current idea (this might change):


Triangles: log2(n+1) * 10000
Entities:  log2(n+1)  * 200
Materials:  log2(n+1) * 300
Textures:  log2(n+1) * 10

If any content exceeds parcel boundaries, the preview will display highlight that content in red. Height is restricted to log2(n+1)  * 20 meters where n is the number of parcels included in the scene.
