### ISSUE TITLE
dcl start --> node errors: reader.skipField is not a function

### ISSUE THREAD

**Issue by angelo-italy** [decentraland/cli#856]
Hi,
i'm trying to start project but on 'dcl start' node return errors: "reader.skipField is not a function"

**Environment**
windows 11
dcl cli 3.12.2 
node: tried with many version from 16.16.0 until the current lts
nvm-win: tried with and without it.

# What?
Here it is terminal log:

✔ Latest SDK installation found.
✔ Checking decentraland libraries

> dcl-project@1.0.0 watch
> build-ecs --watch

> dev mode: true
> working directory: D:\webprojectsIDT\firstProject

> processing D:/webprojectsIDT/firstProject/src/game.ts
> bundling:
  - node_modules\@dcl\amd\dist\amd.js
  - node_modules\decentraland-ecs\dist\src\index.js
  - src\game.ts
> writing D:/webprojectsIDT/firstProject/bin/game.js
> writing D:/webprojectsIDT/firstProject/bin/game.js.lib

The compiler is watching file changes...

[HPM] Proxy created: /  -> https://peer.decentraland.org/
[HPM] Proxy created: /  -> https://peer.decentraland.org/

Preview server is now running

  Available on:

    http://127.0.0.1:8000?position=0%2C0&SCENE_DEBUG_PANEL
    http://192.168.1.87:8000?position=0%2C0&SCENE_DEBUG_PANEL

  Details:

Press CTRL+C to exit

Acquiring comms connection.
C:\Users\angel\AppData\Roaming\nvm\v16.16.0\node_modules\decentraland\dist\lib\proto\broker.js:107
                reader.skipField();
                         ^

**TypeError: reader.skipField is not a function**
    at Function.proto.protocol.CoordinatorMessage.deserializeBinaryFromReader (C:\Users\angel\AppData\Roaming\nvm\v16.16.0\node_modules\decentraland\dist\lib\proto\broker.js:107:24)
    at Function.proto.protocol.CoordinatorMessage.deserializeBinary 

=============================

Browser open and after some seconds: 
![image](https://user-images.githubusercontent.com/17794839/194716170-64d65357-4889-4d96-aa62-e0c8abc3cf0e.png)

...

Any suggestions ?
Thank you.

...

**Comment by menduz** [comment]
Hello, thanks for reporting, we identified the issue and published a possible fix to `npm i -g decentraland@next`.

Would you check if that fixes the problem for you?

Thanks for contributing!

**Comment by pvtallulah** [comment]
Hi, had the same issue as @angelo-italy 
Windows: 10 
node: 16.15.1
installing with ```npm i -g decentraland@next``` solved the issue for me.
Thanks.

**Comment by angelo-italy** [comment]
Hi,
installing with @next release issue solved for me too.
Thank you guys !
