### ISSUE TITLE
x-axis land coordinates reversed

### ISSUE THREAD

**Issue by dafky2000** [decentraland/cli#91]
I've mapped out the layout of my parcels but the x-axis seems reversed. 

```
-2,4 | -1,4 
-2,3 | -1,3 
-2,2 | -1,2 
-2,1 | -1,1 | 0,1
     | -1,0 | 0,0
```
``` javascript
"parcels": ["-2,4","-1,4","-2,3","-1,3","-2,2","-1,2","-2,1","-1,1","0,1","-1,0","0,0"],
```

But it is being mapped out like so

![screenshot_2018-03-13_21-45-43](https://user-images.githubusercontent.com/2653187/37400398-34a6b742-275b-11e8-9778-345728705779.png)

**Comment by eordano** [comment]
Working on it! Thanks a lot Dan

**Comment by kfarr** [comment]
yes noticed the same thing glad it wasn't just me...

**Comment by dafky2000** [comment]
hahah I couldn't tell you guys how many times I reviewed my parcel definition... Thought I was just being daft! Nope, someone else was ;) :p

**Comment by dafky2000** [comment]
No PR?

**Comment by menduz** [comment]
Yes, but in an internal repo, you cannot see it until we make it public
