### ISSUE TITLE
Add deployment properties to the metrics

### ISSUE THREAD

**Issue by pentreathm** [decentraland/cli#943]
When sending deployment metrics, add the following properties 
isWorld
sceneId 
targetContentServer
worldName

**Comment by menduz** [comment]
These metrics can be overwritten with disabled analytics. I recommend to track them server side, when the deployment is received

**Comment by pentreathm** [comment]
we are adding this data here because we already have a metric for the deployment that just needs to be enriched and having it here would also publish data for all servers, foundation and externally hosted
