### ISSUE TITLE
Error: `dcl init` Event is not defined, run "dcl help init" for more info.

### ISSUE THREAD

**Issue by sym2121304** [decentraland/cli#968]
# What? 

... Error: `dcl init` Event is not defined, run "dcl help init" for more info.

# Why? 

... 
<img width="255" alt="image" src="https://github.com/decentraland/cli/assets/18527319/5c758a2b-3fb8-4d8f-b63a-af1fd08a274c">

<img width="243" alt="image" src="https://github.com/decentraland/cli/assets/18527319/76513be6-550c-4de6-953f-e2075dd8f8fb">

**Comment by sym2121304** [comment]
Have already solved

**Comment by FamaNiasse** [comment]
Hi @sym2121304 can you tell me how did you fix the issue because i have the same error message.
Thx you for your help
